# Generated by Django 4.2 on 2023-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apodo', models.CharField(max_length=30)),
                ('dt', models.CharField(max_length=30)),
                ('Año_de_Creacion', models.CharField(max_length=4)),
            ],
        ),
    ]
