# Generated by Django 4.2 on 2023-04-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_alter_equipo_año_de_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='Año_de_Creacion',
            new_name='anio_de_creacion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Apodo',
            new_name='apodo',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Dt',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
