# Generated by Django 4.2 on 2023-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_paleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paleta',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
