# Generated by Django 4.2 on 2023-05-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0008_equipo_escudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='avatar',
            new_name='escudo',
        ),
    ]
