# Generated by Django 4.2 on 2023-05-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_extradata_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradata',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
