# Generated by Django 4.2 on 2023-05-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_extradata_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extradata',
            name='descripcion',
        ),
    ]
