# Generated by Django 4.2 on 2023-05-23 15:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_extradata_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradata',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
